version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: BOKOV
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432" #5432 vneshnij zanjat, poetomy 5431 na vnutrennij

  app:
    #image: python:3.11 #tak kak dockerfile to build, bez- propisivat psycopg nizhe
    build: . 
    container_name: python_container
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    #command: python3 2nd_att.py
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: BOKOV
      DB_USER: user
      DB_PASSWORD: password